baseUrl: "https://iiif.ub.uni-leipzig.de/"
katalogUrl: "https://katalog.ub.uni-leipzig.de/urn/"
manifestFilename: "manifest.json"
isUBLImageService: true
imageServiceBaseUrl: "https://iiif.ub.uni-leipzig.de/iiif"
imageServiceImageDirPrefix: "/j2k/"
imageServiceFileExtension: ".jpx"
imageServiceContext: "http://iiif.io/api/image/2/context.json"
imageServiceProfile: "http://iiif.io/api/image/2/level1.json"
sequenceContext: "/sequence"
canvasContext: "/canvas"
annotationContext: "/anno"
rangeContext: "/range"
license: "https://creativecommons.org/publicdomain/mark/1.0/"
attributionLicenseNote: "No Copyright - Public Domain Marked"
attributionKey: "Provided by "
